Repository alejandrodelcs/algo3_tp2, pull requests merged in 2023-06, with the labels that each got.

#37 16 task: Create Occupiable interface
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/GameBoard/NotOccupiable.java
  src/main/java/edu/fiuba/algo3/modelo/GameBoard/Occupiable.java
  src/main/java/edu/fiuba/algo3/modelo/GameBoard/Occupied.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Dirt.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Path.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Plot.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Stone.java
  src/main/test/edu/fiuba/algo3/entrega_1/AlgoDefenseTest.java
Labels: refactor, feature, Implementing

#43 42 Refactor: apply factory pattern to towers and its tests
  src/main/java/edu/fiuba/algo3/modelo/defense/SilverTower.java
  src/main/java/edu/fiuba/algo3/modelo/defense/TowerFactory.java
  src/main/java/edu/fiuba/algo3/modelo/defense/WhiteTower.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/TowerDoesNotExist.java
  src/main/java/edu/fiuba/algo3/modelo/player/Player.java
  src/main/test/edu/fiuba/algo3/entrega_1/PlotTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/TowerTest.java
Labels: refactor, Testing

#54 51 task create class diagrams
  diagrams/classes/algoDefense/classDiagrm.puml
  diagrams/classes/algoDefense/model/AlgoDefense_class.puml
  diagrams/classes/algoDefense/model/Credit.puml
  diagrams/classes/algoDefense/model/damage/Damage.puml
  diagrams/classes/algoDefense/model/defense/ConstructionState.puml
  diagrams/classes/algoDefense/model/defense/Defense_class_diagram.puml
  diagrams/classes/algoDefense/model/defense/OperationalState.puml
  diagrams/classes/algoDefense/model/defense/SilverTower.puml
  diagrams/classes/algoDefense/model/defense/State.puml
  diagrams/classes/algoDefense/model/defense/State_class_diagram.puml
  diagrams/classes/algoDefense/model/defense/Tower.puml
  diagrams/classes/algoDefense/model/defense/TowerFactory.puml
  diagrams/classes/algoDefense/model/defense/Tower_class_diagram.puml
  diagrams/classes/algoDefense/model/defense/WhiteTower.puml
  diagrams/classes/algoDefense/model/enemy/Ant.puml
  diagrams/classes/algoDefense/model/enemy/Enemy.puml
  diagrams/classes/algoDefense/model/enemy/EnemyFactory.puml
  diagrams/classes/algoDefense/model/enemy/Enemy_classes_diagram.puml
  diagrams/classes/algoDefense/model/enemy/Spider.puml
  diagrams/classes/algoDefense/model/facade/EnemyFacade.puml
  diagrams/classes/algoDefense/model/facade/GameboardFacade.puml
  diagrams/classes/algoDefense/model/gameboard/Available.puml
  diagrams/classes/algoDefense/model/gameboard/Dirt.puml
  diagrams/classes/algoDefense/model/gameboard/GameBoard.puml
  diagrams/classes/algoDefense/model/gameboard/GameBoard_class_diagram.puml
  diagrams/classes/algoDefense/model/gameboard/NotPlotAvailability.puml
  diagrams/classes/algoDefense/model/gameboard/Occupied.puml
  diagrams/classes/algoDefense/model/gameboard/Path.puml
  diagrams/classes/algoDefense/model/gameboard/Plot.puml
  diagrams/classes/algoDefense/model/gameboard/PlotAvailability.puml
  diagrams/classes/algoDefense/model/gameboard/Plot_class_diagram.puml
  diagrams/classes/algoDefense/model/gameboard/Plots_class_diagram.puml
  diagrams/classes/algoDefense/model/gameboard/Stone.puml
  diagrams/classes/algoDefense/model/health/Damageable.puml
  diagrams/classes/algoDefense/model/health/Health.puml
  diagrams/classes/algoDefense/model/health/Health_class_diagram.puml
  diagrams/classes/algoDefense/model/health/NotDamageable.puml
  diagrams/classes/algoDefense/model/parser/EnemiesParser.puml
  diagrams/classes/algoDefense/model/parser/MapParser.puml
  diagrams/classes/algoDefense/model/player/Player.puml
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/Credit.java
  src/main/java/edu/fiuba/algo3/modelo/Turn.java
  src/main/java/edu/fiuba/algo3/modelo/defense/ConstructionState.java
  src/main/java/edu/fiuba/algo3/modelo/defense/OperationalState.java
  src/main/java/edu/fiuba/algo3/modelo/defense/State.java
  src/main/java/edu/fiuba/algo3/modelo/defense/Tower.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Ant.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Enemy.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Spider.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Dirt.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/GameBoard.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Plot.java
  src/main/java/edu/fiuba/algo3/modelo/player/Player.java
  src/main/test/edu/fiuba/algo3/entrega_1/AlgoDefenseTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/CreditTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/PlayerTest.java
Labels: UML

#63 refactor: Tower class
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/Turn.java
  src/main/java/edu/fiuba/algo3/modelo/defense/ConstructionState.java
  src/main/java/edu/fiuba/algo3/modelo/defense/OperationalState.java
  src/main/java/edu/fiuba/algo3/modelo/defense/Range.java
  src/main/java/edu/fiuba/algo3/modelo/defense/SilverTower.java
  src/main/java/edu/fiuba/algo3/modelo/defense/SilverTowerFactory.java
  src/main/java/edu/fiuba/algo3/modelo/defense/State.java
  src/main/java/edu/fiuba/algo3/modelo/defense/Tower.java
  src/main/java/edu/fiuba/algo3/modelo/defense/TowerFactory.java
  src/main/java/edu/fiuba/algo3/modelo/defense/WhiteTower.java
  src/main/java/edu/fiuba/algo3/modelo/defense/WhiteTowerFactory.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Enemy.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/GameBoard.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Plot.java
  src/main/java/edu/fiuba/algo3/modelo/player/Player.java
  src/main/test/edu/fiuba/algo3/entrega_1/AlgoDefenseTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/TowerTest.java
Labels: refactor, Implementing, Testing

#65 Refactor: Tower class
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/Turn.java
  src/main/java/edu/fiuba/algo3/modelo/attack/Attack.java
  src/main/java/edu/fiuba/algo3/modelo/attack/SimpleRangeAttack.java
  src/main/java/edu/fiuba/algo3/modelo/defense/ConstructionState.java
  src/main/java/edu/fiuba/algo3/modelo/defense/Defense.java
  src/main/java/edu/fiuba/algo3/modelo/defense/OperationalState.java
  src/main/java/edu/fiuba/algo3/modelo/defense/Range.java
  src/main/java/edu/fiuba/algo3/modelo/defense/SandyTrap.java
  src/main/java/edu/fiuba/algo3/modelo/defense/State.java
  src/main/java/edu/fiuba/algo3/modelo/defense/Tower.java
  src/main/java/edu/fiuba/algo3/modelo/defense/TowerFactory.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/GameBoard.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/NotPlotAvailability.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Occupied.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Plot.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/PlotAvailability.java
  src/main/java/edu/fiuba/algo3/modelo/player/Player.java
  src/main/test/edu/fiuba/algo3/entrega_1/AlgoDefenseTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/PlotTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/TowerTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/TurnTest.java
Labels: refactor, Implementing, Testing

#75 68 task: add log class
  src/main/java/edu/fiuba/algo3/modelo/Log.java
  src/main/java/module-info.java
  src/main/test/edu/fiuba/algo3/entrega_2/AlgoDefenseTwoTest.java
Labels: feature, Implementing, Testing

#79 The enemies disappear after attacking the player
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/GameBoard.java
  src/main/java/edu/fiuba/algo3/modelo/health/Damageable.java
  src/main/java/edu/fiuba/algo3/modelo/health/Health.java
  src/main/java/edu/fiuba/algo3/modelo/player/Player.java
  src/main/test/edu/fiuba/algo3/entrega_2/AlgoDefenseTwoTest.java
Labels: Implementing, Testing

#82 Added a situation where the player wins the game
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/app.log
  src/main/java/edu/fiuba/algo3/modelo/turn/Turn.java
Labels: Implementing, Testing

#86 feature: add ant credits increase
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/Log.java
  src/main/java/edu/fiuba/algo3/modelo/app.log
  src/main/java/edu/fiuba/algo3/modelo/credit/Credit.java
  src/main/java/edu/fiuba/algo3/modelo/player/Player.java
  src/main/java/edu/fiuba/algo3/modelo/turn/Turn.java
  src/main/test/edu/fiuba/algo3/entrega_2/AlgoDefenseTwoTest.java
Labels: feature, Implementing, Testing

#95 refactor: Add game states in AlgoDefense
  src/main/java/edu/fiuba/algo3/controllers/Board.java
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/algodefense/Active.java
  src/main/java/edu/fiuba/algo3/modelo/algodefense/GameOver.java
  src/main/java/edu/fiuba/algo3/modelo/algodefense/GameState.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/Gameover.java
  src/main/java/edu/fiuba/algo3/modelo/player/Player.java
  src/main/test/edu/fiuba/algo3/entrega_1/AlgoDefenseTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/PlayerTest.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/TowerTest.java
  src/main/test/edu/fiuba/algo3/entrega_2/AlgoDefenseTwoTest.java
  src/main/test/edu/fiuba/algo3/entrega_2/SandyTrapTest.java
Labels: refactor, Implementing, Testing

#116 Sound effects
  src/main/java/edu/fiuba/algo3/controllers/Board.java
  src/main/java/edu/fiuba/algo3/controllers/Signup.java
  src/main/java/edu/fiuba/algo3/controllers/Sound.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/ErrorIdentifierDoesNotMatchAnyLoadedSong.java
  src/main/resources/sound/build-defense.mp3
  src/main/resources/sound/insufficient-credits.wav
  src/main/resources/sound/level-lose.wav
  src/main/resources/sound/level-win.wav
  src/main/resources/sound/spider_attack.mp3
  src/main/resources/sound/tower-attack.mp3
Labels: feature

#121 Fix defenses
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/defense/Defense.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Ant.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Enemy.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Mole.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Owl.java
  src/main/java/edu/fiuba/algo3/modelo/enemy/Spider.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Dirt.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/GameBoard.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Path.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Plot.java
  src/main/java/edu/fiuba/algo3/modelo/turn/Turn.java
Labels: bug

#126 refactor: remove unused exceptions
  src/main/java/edu/fiuba/algo3/modelo/exceptions/EnemyDoesNotExist.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/EnemyIsOutOfRange.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/NonTowerContructibleArea.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/NonTrapConstructibleArea.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/PlayerIsDeadGameOver.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/TowerDoesNotExist.java
  src/main/java/edu/fiuba/algo3/modelo/exceptions/TowerIsUnderConstruction.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/Dirt.java
  src/main/java/edu/fiuba/algo3/modelo/player/Player.java
  src/main/test/edu/fiuba/algo3/entrega_1/model/PlayerTest.java
Labels: refactor

#127 add enemy spawn sounds
  src/main/java/edu/fiuba/algo3/controllers/Board.java
  src/main/java/edu/fiuba/algo3/modelo/gameboard/GameBoard.java
  src/main/resources/sound/Ant-Spawn.wav
  src/main/resources/sound/Mole-Spawn.wav
  src/main/resources/sound/Owl-Spawn.wav
  src/main/resources/sound/spawn-Owl.mp3
  src/main/resources/sound/spider-spawn.mp3
Labels: feature

#128 reset Logger
  src/main/java/edu/fiuba/algo3/modelo/AlgoDefense.java
  src/main/java/edu/fiuba/algo3/modelo/Logger.java
Labels: bug
